version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: my-room-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "fame1234"
      MYSQL_DATABASE: "reservation_db"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "fame1234"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
